services:
  - type: web
    name: diabetic-retinopathy-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11